name: 'Jennifer Schafer : Creative Savant'
favicon: null
layout_spectrum: 0.5870390748605132
typography_spectrum: 0.9251014171168208
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4173849234357476
  lightness: 0.9267734952736646
  saturation: 0.040705056162551045
  rhythmicContrast: 0.8816332556307316
purpose: []
